import { config } from "dotenv";
config({ path: ".env.local" });

import { drizzle } from "drizzle-orm/neon-http";
import { neon } from "@neondatabase/serverless";
import * as schema from "../src/db/schema";

const sql = neon(process.env.DATABASE_URL!);
const db = drizzle(sql, { schema });

// Catálogo de certificaciones
const certs = [
  { slug: "fap", nombre: "Certificación FAP", organismo: "Federación de Pádel de Chile (FAP)", pais: "CL", pesoCredibilidad: 100 },
  { slug: "rfep", nombre: "Certificación RFEP", organismo: "Real Federación Española de Pádel", pais: "ES", pesoCredibilidad: 100 },
  { slug: "rpt", nombre: "RPT Certified Coach", organismo: "Register of Padel Trainers", pais: "INT", pesoCredibilidad: 85 },
  { slug: "fap-junior", nombre: "Instructor Junior FAP", organismo: "Federación de Pádel de Chile (FAP)", pais: "CL", pesoCredibilidad: 70 },
  { slug: "padel-pro-tour", nombre: "Padel Pro Tour Coach", organismo: "Padel Pro Tour", pais: "INT", pesoCredibilidad: 90 },
];

const profesData: (typeof schema.profes.$inferInsert)[] = [
  {
    slug: "rodrigo-silva-santiago",
    nombre: "Rodrigo",
    apellido: "Silva",
    genero: "hombre",
    ciudad: "Santiago",
    comuna: "Providencia",
    pais: "CL",
    bioCorta: "Ex-jugador de circuito nacional. 12 años formando jugadores de Cat 5 a Cat 2 en Santiago.",
    bioMd: `# Rodrigo Silva — Profe de Pádel en Providencia\n\nComencé a jugar pádel a los 18 años y competí en el circuito nacional durante 8 temporadas. Hoy me dedico full-time a enseñar, con foco en la transición Cat 4 → 2.\n\nMi metodología está basada en la repetición técnica con contexto táctico real. No trabajo en vacío: cada drill tiene un por qué y un cuándo usarlo.`,
    sobreMiMd: "12 años enseñando en Santiago. Ex-competidor del circuito FPCH. Formé a más de 200 alumnos.",
    metodologiaMd: "Video análisis en cada clase. Drill → aplicación táctica → puntos. Progresión medible cada 4 semanas.",
    anosExperiencia: 12,
    exJugadorPro: true,
    exJugadorProCircuito: "FPCH",
    certificaciones: ["FAP", "RPT"],
    idiomas: ["es"],
    categoriasQueEnsena: [2, 3, 4, 5],
    especialidades: ["tecnica_avanzada", "vibora", "tactica", "transicion_competitiva"],
    modalidades: ["individual", "pareja", "grupo_3_4"],
    precioIndividual60min: 45000,
    precioIndividual90min: 65000,
    precioPareja60min: 30000,
    precioGrupo60min: 22000,
    permitePaquetes: true,
    descuentoPaquete10Pct: 15,
    whatsapp: "+56912345678",
    instagram: "rodrigopadel_scl",
    telefonoVisible: false,
    verificado: true,
    certificacionVerificada: true,
    destacado: true,
    estado: "activo",
    ratingPromedio: 4.9,
    reviewsCount: 47,
    clasesDadasCount: 340,
    alumnosRecurrentesCount: 28,
    respuestaPromedioHoras: 1.5,
    publishedAt: new Date("2024-06-01"),
    nuevo: false,
  },
  {
    slug: "camila-torres-las-condes",
    nombre: "Camila",
    apellido: "Torres",
    genero: "mujer",
    ciudad: "Santiago",
    comuna: "Las Condes",
    pais: "CL",
    bioCorta: "Especialista en juego femenino e iniciación adulta. Ambiente 100% cómodo para comenzar desde cero.",
    bioMd: `# Camila Torres — Clases de Pádel en Las Condes\n\nLlevo 7 años enseñando pádel con especialización en iniciación adulta y juego femenino. Soy certificada FAP y tengo formación en psicología deportiva.\n\nMi clase ideal: alguien que nunca tocó una pala y quiere aprender bien desde el primer día. Sin apuros, sin vergüenza.`,
    sobreMiMd: "Certificada FAP. Especialista en iniciación adulta y juego femenino. 7 años de experiencia.",
    metodologiaMd: "Aprendo cómo aprendés vos. Adapto el ritmo a tu nivel. Sin comparaciones, solo progresión.",
    anosExperiencia: 7,
    exJugadorPro: false,
    certificaciones: ["FAP"],
    idiomas: ["es", "en"],
    categoriasQueEnsena: [4, 5, 6],
    especialidades: ["juego_femenino", "iniciacion_adulta", "mental_game"],
    modalidades: ["individual", "pareja", "clinica"],
    precioIndividual60min: 35000,
    precioIndividual90min: 50000,
    precioPareja60min: 25000,
    precioClinica60min: 18000,
    permitePaquetes: true,
    descuentoPaquete10Pct: 10,
    whatsapp: "+56998765432",
    instagram: "camilapadel_stgo",
    telefonoVisible: true,
    verificado: true,
    certificacionVerificada: true,
    destacado: false,
    estado: "activo",
    ratingPromedio: 4.8,
    reviewsCount: 31,
    clasesDadasCount: 210,
    alumnosRecurrentesCount: 19,
    respuestaPromedioHoras: 2.0,
    publishedAt: new Date("2024-08-15"),
    nuevo: false,
  },
  {
    slug: "martin-benitez-vitacura",
    nombre: "Martín",
    apellido: "Benítez",
    genero: "hombre",
    ciudad: "Santiago",
    comuna: "Vitacura",
    pais: "CL",
    bioCorta: "Profe competitivo Cat 1. Entreno jugadores de torneo con foco en mental game y presión de red.",
    bioMd: `# Martín Benítez — Clases de Pádel en Vitacura\n\nActualmente compito en categoría abierta a nivel nacional y combino con la enseñanza. Trabajo exclusivamente con jugadores Cat 1-3 que quieren dar el salto a torneos.`,
    sobreMiMd: "Jugador activo Cat 1. Profe con 5 años de experiencia en el segmento competitivo.",
    metodologiaMd: "Entreno mental + técnico. Simulamos situaciones de partido real en cada sesión.",
    anosExperiencia: 5,
    exJugadorPro: false,
    certificaciones: ["RPT"],
    idiomas: ["es"],
    categoriasQueEnsena: [1, 2, 3],
    especialidades: ["mental_game", "tactica", "transicion_competitiva", "tecnica_avanzada"],
    modalidades: ["individual", "pareja"],
    precioIndividual60min: 55000,
    precioIndividual90min: 80000,
    precioPareja60min: 38000,
    permitePaquetes: false,
    whatsapp: "+56987654321",
    telefonoVisible: false,
    verificado: true,
    certificacionVerificada: true,
    destacado: false,
    estado: "activo",
    ratingPromedio: 4.7,
    reviewsCount: 18,
    clasesDadasCount: 120,
    alumnosRecurrentesCount: 9,
    respuestaPromedioHoras: 3.0,
    publishedAt: new Date("2024-09-01"),
    nuevo: false,
  },
  {
    slug: "sofia-moran-buenos-aires",
    nombre: "Sofía",
    apellido: "Morán",
    genero: "mujer",
    ciudad: "Buenos Aires",
    comuna: "Palermo",
    pais: "AR",
    bioCorta: "Profe certificada RFEP. Formación en España + 6 años en Buenos Aires. Especialidad: víbora y salidas de pared.",
    bioMd: `# Sofía Morán — Clases de Pádel en Palermo, Buenos Aires\n\nEstudié pádel en España con certificación RFEP y volví a Buenos Aires para enseñar con la metodología europea. Especialidad en el punto de contacto alto y la víbora.`,
    sobreMiMd: "Certificada RFEP España. 6 años en Buenos Aires. Especialista en golpes técnicos avanzados.",
    metodologiaMd: "Metodología europea: técnica primero, táctica después. Video análisis opcional.",
    anosExperiencia: 8,
    exJugadorPro: false,
    certificaciones: ["RFEP"],
    idiomas: ["es", "en"],
    categoriasQueEnsena: [3, 4, 5],
    especialidades: ["vibora", "tecnica_avanzada", "juego_femenino"],
    modalidades: ["individual", "pareja", "online_video_analisis"],
    precioIndividual60min: 12000,
    precioIndividual90min: 17000,
    precioPareja60min: 8500,
    precioVideoAnalisis: 8000,
    monedaBase: "ARS",
    permitePaquetes: true,
    descuentoPaquete10Pct: 12,
    whatsapp: "+5491112345678",
    instagram: "sofiapadel_bsas",
    atiendeOnline: true,
    telefonoVisible: false,
    verificado: true,
    certificacionVerificada: true,
    destacado: true,
    estado: "activo",
    ratingPromedio: 4.9,
    reviewsCount: 52,
    clasesDadasCount: 420,
    alumnosRecurrentesCount: 35,
    respuestaPromedioHoras: 1.0,
    publishedAt: new Date("2024-03-15"),
    nuevo: false,
  },
  {
    slug: "diego-herrera-buenos-aires",
    nombre: "Diego",
    apellido: "Herrera",
    genero: "hombre",
    ciudad: "Buenos Aires",
    comuna: "Belgrano",
    pais: "AR",
    bioCorta: "Profe con foco en niños y adultos mayores. 10 años de experiencia en escuelas de pádel en BsAs.",
    bioMd: `# Diego Herrera — Clases de Pádel en Belgrano, Buenos Aires\n\nTrabajé 10 años dirigiendo la escuela de pádel del Club Ciudad de Buenos Aires. Mi especialidad son los grupos de niños (6-14 años) y adultos que empiezan después de los 40.`,
    sobreMiMd: "Ex-director de escuela de pádel. Especialista en iniciación infantil y adultos de primera vez.",
    metodologiaMd: "Para niños: juego y competencia sana. Para adultos: técnica limpia sin presión.",
    anosExperiencia: 10,
    exJugadorPro: false,
    certificaciones: ["RPT"],
    idiomas: ["es"],
    categoriasQueEnsena: [5, 6],
    especialidades: ["ninos", "iniciacion_adulta"],
    modalidades: ["individual", "grupo_3_4", "clinica", "intensivo_fin_de_semana"],
    precioIndividual60min: 10000,
    precioGrupo60min: 6000,
    precioClinica60min: 5500,
    monedaBase: "ARS",
    permitePaquetes: true,
    descuentoPaquete10Pct: 20,
    whatsapp: "+5491187654321",
    instagram: "padel_ninos_bsas",
    telefonoVisible: true,
    verificado: true,
    certificacionVerificada: false,
    destacado: false,
    estado: "activo",
    ratingPromedio: 4.6,
    reviewsCount: 28,
    clasesDadasCount: 580,
    alumnosRecurrentesCount: 45,
    respuestaPromedioHoras: 4.0,
    publishedAt: new Date("2024-01-10"),
    nuevo: false,
  },
  {
    slug: "valentina-rios-montevideo",
    nombre: "Valentina",
    apellido: "Ríos",
    genero: "mujer",
    ciudad: "Montevideo",
    comuna: "Pocitos",
    pais: "UY",
    bioCorta: "Única profe certificada FAP en Montevideo. Online disponible para todo Uruguay. Cat 3-6.",
    bioMd: `# Valentina Ríos — Clases de Pádel en Montevideo y Online\n\nSoy la única profe con certificación FAP (Chile) afincada en Uruguay. Doy clases presenciales en Pocitos y Carrasco, y online para todo el país.`,
    sobreMiMd: "Certificada FAP. Presencial en Montevideo + clases online para todo Uruguay.",
    metodologiaMd: "Clases estructuradas con objetivo semanal. Para online: grabación del alumno + análisis comentado.",
    anosExperiencia: 4,
    exJugadorPro: false,
    certificaciones: ["FAP"],
    idiomas: ["es"],
    categoriasQueEnsena: [3, 4, 5, 6],
    especialidades: ["iniciacion_adulta", "juego_femenino", "tactica"],
    modalidades: ["individual", "pareja", "online_video_analisis"],
    precioIndividual60min: 1800,
    precioPareja60min: 1200,
    precioVideoAnalisis: 1500,
    monedaBase: "UYU",
    permitePaquetes: true,
    descuentoPaquete10Pct: 10,
    whatsapp: "+59812345678",
    instagram: "valentinapadel_uy",
    atiendeOnline: true,
    telefonoVisible: true,
    verificado: true,
    certificacionVerificada: true,
    destacado: false,
    estado: "activo",
    ratingPromedio: 4.8,
    reviewsCount: 14,
    clasesDadasCount: 95,
    alumnosRecurrentesCount: 11,
    respuestaPromedioHoras: 2.5,
    publishedAt: new Date("2025-01-05"),
    nuevo: true,
  },
  {
    slug: "andres-molina-nunoa",
    nombre: "Andrés",
    apellido: "Molina",
    genero: "hombre",
    ciudad: "Santiago",
    comuna: "Ñuñoa",
    pais: "CL",
    bioCorta: "Preparador físico + profe de pádel. El único enfoque integral en Santiago.",
    bioMd: `# Andrés Molina — Pádel + Preparación Física en Ñuñoa\n\nSoy kinesiólogo y profe de pádel. Combino análisis de movimiento con instrucción técnica. Si tenés una lesión recurrente o querés mejorar tu físico para el pádel, soy tu profe.`,
    sobreMiMd: "Kinesiólogo + profe de pádel. Foco en preparación física específica para el juego.",
    metodologiaMd: "Diagnóstico físico inicial → plan de trabajo paralelo técnico-físico → seguimiento mensual.",
    anosExperiencia: 6,
    exJugadorPro: false,
    certificaciones: ["FAP"],
    idiomas: ["es"],
    categoriasQueEnsena: [2, 3, 4, 5],
    especialidades: ["preparacion_fisica", "tecnica_avanzada", "tactica"],
    modalidades: ["individual", "intensivo_fin_de_semana"],
    precioIndividual60min: 50000,
    precioIndividual90min: 72000,
    permitePaquetes: true,
    descuentoPaquete10Pct: 10,
    whatsapp: "+56976543210",
    telefonoVisible: false,
    verificado: true,
    certificacionVerificada: true,
    destacado: false,
    estado: "activo",
    ratingPromedio: 4.7,
    reviewsCount: 22,
    clasesDadasCount: 175,
    alumnosRecurrentesCount: 16,
    respuestaPromedioHoras: 5.0,
    publishedAt: new Date("2024-07-20"),
    nuevo: false,
  },
  {
    slug: "jorge-cantu-online",
    nombre: "Jorge",
    apellido: "Cantú",
    genero: "hombre",
    ciudad: "Buenos Aires",
    comuna: "Recoleta",
    pais: "AR",
    bioCorta: "Profe 100% online. Video análisis de tu juego + plan personalizado mensual. Atiendo toda Latinoamérica.",
    bioMd: `# Jorge Cantú — Análisis de Video y Clases Online para Pádel\n\nMi producto es el video análisis. Grabás tus partidos, yo los analizo y te entrego un informe detallado con los 3 puntos específicos en los que debés trabajar ese mes. Online para toda LATAM.`,
    sobreMiMd: "Especialista en análisis de video. 100% online. Clientes en Argentina, Chile, Uruguay y México.",
    metodologiaMd: "Análisis de video → 3 prioridades mensuales → drills personalizados → check a las 2 semanas.",
    anosExperiencia: 9,
    exJugadorPro: true,
    exJugadorProCircuito: "A1 Padel",
    certificaciones: ["RPT", "RFEP"],
    idiomas: ["es", "en"],
    categoriasQueEnsena: [1, 2, 3, 4],
    especialidades: ["tecnica_avanzada", "tactica", "mental_game", "transicion_competitiva", "vibora"],
    modalidades: ["online_video_analisis"],
    precioIndividual60min: 15000,
    precioVideoAnalisis: 12000,
    monedaBase: "ARS",
    atiendeOnline: true,
    permitePaquetes: true,
    descuentoPaquete10Pct: 15,
    whatsapp: "+5491165432109",
    instagram: "jorgepadel_analisis",
    telefonoVisible: false,
    verificado: true,
    certificacionVerificada: true,
    destacado: false,
    estado: "activo",
    ratingPromedio: 4.9,
    reviewsCount: 63,
    clasesDadasCount: 0,
    alumnosRecurrentesCount: 41,
    respuestaPromedioHoras: 6.0,
    publishedAt: new Date("2023-11-01"),
    nuevo: false,
  },
];

async function main() {
  console.log("Seeding certificaciones catálogo...");
  for (const cert of certs) {
    await db.insert(schema.certificacionesCatalogo).values(cert).onConflictDoNothing();
  }
  console.log(`  ✓ ${certs.length} certificaciones`);

  console.log("Seeding profes...");
  for (const profe of profesData) {
    await db.insert(schema.profes).values(profe).onConflictDoUpdate({
      target: schema.profes.slug,
      set: { ...profe },
    });
  }
  console.log(`  ✓ ${profesData.length} profes`);

  console.log("Done.");
}

main().catch((e) => { console.error(e); process.exit(1); });
